name: Sitemap

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: sitemap

jobs:

  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AMAZON_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AMAZON_SECRET_KEY }}
    - run: make sitemap

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [af-south-1, ap-east-1, ap-south-1, ap-southeast-1, ap-southeast-2, ca-central-1, eu-central-1, eu-west-2, me-south-1, sa-east-1, us-west-2]
    steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AMAZON_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AMAZON_SECRET_KEY }}
    - run: aws s3 sync --delete --exact-timestamp --source-region eu-west-2 --region ${{ matrix.region }} s3://www.surrealdb.com s3://www.${{ matrix.region }}.surrealdb.com
